# Generated by Django 6.0.8 on 2026-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_stop_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='profit_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
