# Generated by Django 6.0.8 on 2026-10-01 06:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_profit_taking'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='equity_peak',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=18),
        ),
    ]
