# Generated by Django 6.0.8 on 2026-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_kill_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='ladder_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
