# Generated by Django 6.0.8 on 2026-10-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_ladder_buys'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='ema',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='moves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='reentry_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='reentry_move',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='stop_move',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
