# Generated by Django 6.0.8 on 2026-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_reentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
