# Generated by Django 6.0.8 on 2026-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_market_regime'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('phase', models.CharField(default='dca', max_length=7)),
                ('last_buy_move', models.PositiveIntegerField(blank=True, null=True)),
                ('cycle', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
