# Generated by Django 6.0.8 on 2026-10-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filer', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=5)),
                ('side', models.CharField(max_length=4)),
                ('bucket', models.PositiveSmallIntegerField()),
                ('traded_on', models.DateField()),
                ('outcome', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('filer', 'symbol', 'side', 'bucket', 'traded_on'), name='unique_filing')],
            },
        ),
    ]
